using System.Text.RegularExpressions;
using ClosedXML.Excel;
using HakedisOtomasyon.Application.Interfaces;
using HakedisOtomasyon.Domain.Enums;
using Microsoft.Extensions.Logging;

namespace HakedisOtomasyon.Infrastructure.Services;

public class PosMappingService : IPosMappingService
{
    private readonly ILogger<PosMappingService> _logger;
    private readonly IAppPathService _appPaths;
    private readonly IDisciplineProfileService _disciplineProfiles;
    private readonly CurrentDisciplineService _currentDiscipline;

    /// <summary>
    /// Eski (Aşama 3 öncesi) POS dosyası konumu — uygulamanın kendi kurulum klasörü içinde.
    /// Her yeniden yayınlamada (publish) bu klasörün üzerine yazıldığı için kullanıcı
    /// düzenlemeleri kaybolabiliyordu. Sadece Yangın için bir kerelik geçiş kaynağıdır.
    /// </summary>
    private static readonly string LegacyPosFilePath = Path.Combine(
        AppContext.BaseDirectory,
        "Assets", "ReferenceTables", "MasterData",
        "POS_Malzeme_Eslesme.xlsx");

    /// <summary>
    /// Aktif disipline göre güncel POS dosya yolu. Disiplin değiştiğinde (Yangın ↔ Klima)
    /// otomatik olarak doğru klasöre işaret eder — sabit/önceden hesaplanmış DEĞİLDİR.
    /// </summary>
    public string PosFilePath => Path.Combine(
        _disciplineProfiles.GetMasterDataPath(_currentDiscipline.CurrentDiscipline),
        "POS_Malzeme_Eslesme.xlsx");

    private Dictionary<string, string> _exactMap = new(StringComparer.Ordinal);
    private List<(string Key, string PosNo)> _entries = [];
    private DateTime _fileModifiedTime = DateTime.MinValue;
    private DateTime _lastFreshnessCheck = DateTime.MinValue;
    private MechanicalDiscipline? _lastLoadedDiscipline;
    private const int FreshnessThrottleSeconds = 5;

    // Export log için lock
    private readonly object _logLock = new();

    public PosMappingService(
        ILogger<PosMappingService> logger,
        IAppPathService appPaths,
        IDisciplineProfileService disciplineProfiles,
        CurrentDisciplineService currentDiscipline)
    {
        _logger = logger;
        _appPaths = appPaths;
        _disciplineProfiles = disciplineProfiles;
        _currentDiscipline = currentDiscipline;
        // Aşama 3: POS dosyası artık ilgili disiplinin MasterData klasöründe —
        // Desktop\SERVİS OTOMASYONU DATABASE altında, publish sırasında silinmeyen kalıcı konum.
        EnsureMasterDataFile();
        LoadMap();
    }

    /// <summary>
    /// Şablon/eski dosyadan kopyalama SADECE Yangın için yapılır — Klima ve diğer
    /// disiplinlerin POS dosyası yoksa kullanıcı Ayarlar ekranından kendi dosyasını
    /// yükler/oluşturur (Yangın'a özel şablonun Klima'ya kopyalanması yanlış olur).
    /// </summary>
    private void EnsureMasterDataFile()
    {
        try
        {
            var path = PosFilePath;
            if (File.Exists(path)) return; // Kullanıcı dosyası varsa asla dokunma
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);

            if (_currentDiscipline.CurrentDiscipline != MechanicalDiscipline.Fire)
                return; // Diğer disiplinler için otomatik şablon oluşturulmaz

            // 1. Önce eski konumda kullanıcının düzenlemiş olabileceği dosya var mı bak
            if (File.Exists(LegacyPosFilePath))
            {
                File.Copy(LegacyPosFilePath, path);
                _logger.LogInformation("POS dosyası eski konumdan taşındı: {Old} -> {New}", LegacyPosFilePath, path);
                return;
            }

            // 2. Eski dosya da yoksa şablondan oluştur (ilk kurulum)
            var templatePath = FindTemplatePath();
            if (templatePath is null)
            { _logger.LogWarning("POS şablon dosyası bulunamadı."); return; }
            File.Copy(templatePath, path);
            _logger.LogInformation("POS şablon kopyalandı: {P}", path);
        }
        catch (Exception ex) { _logger.LogError(ex, "POS dosyası hazırlama hatası."); }
    }

    private static string? FindTemplatePath()
    {
        const string rel = @"Assets\ReferenceTables\POS_Malzeme_Eslesme_Claude_Hazir.xlsx";
        var p1 = Path.Combine(AppContext.BaseDirectory, rel);
        if (File.Exists(p1)) return p1;
        var p2 = Path.Combine(Directory.GetCurrentDirectory(), rel);
        if (File.Exists(p2)) return p2;
        return null;
    }

    // --- Public API ---

    public string? GetPosNo(string description, string? autoGeneratedType = null)
    {
        if (string.IsNullOrWhiteSpace(description)) return null;
        EnsureFresh();
        return Resolve(description, autoGeneratedType);
    }

    /// <summary>
    /// Export sırasında çağrılır. Önce haritayı tazeler, sonra POS bulur ve log yazar.
    /// </summary>
    public string ResolvePosForExport(string description, string? autoGeneratedType, List<string>? exportLog)
    {
        EnsureFresh();
        var result = Resolve(description, autoGeneratedType) ?? string.Empty;
        exportLog?.Add($"  [{(string.IsNullOrEmpty(result) ? "BOŞ" : result),6}] {description}");
        return result;
    }

    public void Reload()
    {
        LoadMap();
        _logger.LogInformation("POS haritası elle yenilendi.");
    }

    // --- İç çözümleme ---
    private string? Resolve(string description, string? autoGeneratedType)
    {
        // Sülyen/Polisan/Flexi özel POS kuralları YANGIN'a özeldir. Klima'da (veya başka
        // bir disiplinde) açıklama metninde aynı kelimeler geçse bile bu kurallar
        // çalışmamalı — aksi halde Yangın'a özel POS numaraları Klima'ya sızar.
        if (_currentDiscipline.CurrentDiscipline == MechanicalDiscipline.Fire)
        {
            var paintPos = TryGetPaintPos(description, autoGeneratedType);
            if (paintPos != null) return paintPos;

            var flexiPos = TryGetFlexiPos(description);
            if (flexiPos != null) return flexiPos;
        }

        if (_exactMap.Count == 0 && _entries.Count == 0) return null;

        var norm = Normalize(description);
        if (string.IsNullOrWhiteSpace(norm)) return null;

        // 1. Tam eşleşme
        if (_exactMap.TryGetValue(norm, out var pos)) return pos;

        // 2. norm içinde key var mı? (kısa anahtar — uzun açıklama içinde)
        foreach (var (key, posNo) in _entries)
            if (key.Length >= 8 && norm.Contains(key)) return posNo;

        // 3. key içinde norm var mı? (uzun anahtar — kısa açıklama içinde)
        foreach (var (key, posNo) in _entries)
            if (norm.Length >= 8 && key.Contains(norm)) return posNo;

        return null;
    }

    // --- Cache yenileme ---
    private void EnsureFresh()
    {
        // Disiplin değiştiyse (Yangın ↔ Klima) throttle'ı atla — farklı dosyadan okumalı.
        bool disciplineChanged = _lastLoadedDiscipline != _currentDiscipline.CurrentDiscipline;

        var now = DateTime.UtcNow;
        if (!disciplineChanged
            && (now - _lastFreshnessCheck).TotalSeconds < FreshnessThrottleSeconds
            && _exactMap.Count > 0)   // map boşsa throttle'ı atla
            return;
        _lastFreshnessCheck = now;

        var path = PosFilePath;

        // MasterData dosyası yoksa şablon var mı dene (sadece Yangın için otomatik oluşturulur)
        if (!File.Exists(path))
        {
            EnsureMasterDataFile();
            if (!File.Exists(path))
            {
                // Dosya hâlâ yok — boş haritayla devam et, hata verme.
                if (disciplineChanged) { _exactMap = new(StringComparer.Ordinal); _entries = []; _lastLoadedDiscipline = _currentDiscipline.CurrentDiscipline; }
                return;
            }
        }

        try
        {
            var current = File.GetLastWriteTimeUtc(path);
            if (disciplineChanged || current > _fileModifiedTime || _exactMap.Count == 0)
            {
                _logger.LogInformation("POS dosyası değişmiş, disiplin değişti veya harita boş — yenileniyor.");
                LoadMap();
            }
        }
        catch { }
    }

    // --- Excel yükleme ---
    private void LoadMap()
    {
        _lastLoadedDiscipline = _currentDiscipline.CurrentDiscipline;
        var exact   = new Dictionary<string, string>(StringComparer.Ordinal);
        var entries = new List<(string, string)>();

        // Şablona düşme SADECE Yangın için geçerlidir — Klima'nın Yangın'a özel
        // POS eşleşmelerini yanlışlıkla devralmaması gerekir.
        var filePath = File.Exists(PosFilePath)
            ? PosFilePath
            : (_currentDiscipline.CurrentDiscipline == MechanicalDiscipline.Fire ? FindTemplatePath() : null);
        if (filePath is null)
        {
            _logger.LogWarning("POS dosyası bulunamadı: {P}", PosFilePath);
            _exactMap = exact; _entries = entries;
            _fileModifiedTime = DateTime.MinValue;
            return;
        }

        try
        {
            _fileModifiedTime = File.GetLastWriteTimeUtc(filePath);
            using var wb = new XLWorkbook(filePath);

            IXLWorksheet? ws = null;
            foreach (var sheet in wb.Worksheets)
                if (sheet.Name.Equals("POS_Eslesme_Hazir", StringComparison.OrdinalIgnoreCase))
                { ws = sheet; break; }

            if (ws is null)
            {
                _logger.LogWarning("POS_Eslesme_Hazir sayfası yok: {F}", filePath);
                _exactMap = exact; _entries = entries;
                return;
            }

            // Kolon bul
            int posNoCol = -1, programAcikCol = -1, matchKeyCol = -1;
            int lastCol = ws.LastColumnUsed()?.ColumnNumber() ?? 20;
            for (int c = 1; c <= lastCol; c++)
            {
                var h = NormalizeHeader(ws.Cell(1, c).GetString().Trim());
                if (h is "POS" or "POS_NO" or "POSNO") posNoCol = c;
                else if (h == "PROGRAMACIKLAMASI" || h.Contains("PROGRAMACIKLAMA") || h == "ACIKLAMA") programAcikCol = c;
                else if (h is "MATCHKEY" or "MATCH_KEY") matchKeyCol = c;
            }

            if (posNoCol == -1)
            {
                _logger.LogWarning("POS kolonu bulunamadı: {F}", filePath);
                _exactMap = exact; _entries = entries;
                return;
            }

            int lastRow = ws.LastRowUsed()?.RowNumber() ?? 1;
            int loaded = 0;

            for (int r = 2; r <= lastRow; r++)
            {
                var posNo = ws.Cell(r, posNoCol).GetString().Trim();
                if (string.IsNullOrWhiteSpace(posNo)) continue;

                // MatchKey — boşsa ProgramAciklamasi'ndan otomatik üret
                string? matchNorm = null;
                if (matchKeyCol > 0)
                {
                    var mk = ws.Cell(r, matchKeyCol).GetString().Trim();
                    if (string.IsNullOrWhiteSpace(mk) && programAcikCol > 0)
                        mk = ws.Cell(r, programAcikCol).GetString().Trim();
                    if (!string.IsNullOrWhiteSpace(mk))
                    {
                        matchNorm = Normalize(mk);
                        if (!string.IsNullOrWhiteSpace(matchNorm))
                        {
                            exact.TryAdd(matchNorm, posNo);
                            entries.Add((matchNorm, posNo));
                        }
                    }
                }

                // ProgramAciklamasi — ayrıca hem exact hem entries'e ekle
                // BUG FIX: Daha önce sadece exact'a ekleniyordu;
                // contains-fallback için entries'e de eklemek gerekiyor.
                if (programAcikCol > 0)
                {
                    var desc = ws.Cell(r, programAcikCol).GetString().Trim();
                    if (!string.IsNullOrWhiteSpace(desc))
                    {
                        var nd = Normalize(desc);
                        if (!string.IsNullOrWhiteSpace(nd) && nd != matchNorm)
                        {
                            exact.TryAdd(nd, posNo);
                            entries.Add((nd, posNo)); // FIX: entries'e de ekle
                        }
                    }
                }

                loaded++;
            }

            _exactMap = exact;
            _entries  = entries;
            _logger.LogInformation(
                "POS yüklendi: {R} satır, {K} exact, {E} entry. Kaynak: {F}",
                loaded, exact.Count, entries.Count, Path.GetFileName(filePath));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "POS Excel hatası: {P}", filePath);
        }
    }

    // --- Export log yazıcı ---
    public void WriteExportLog(List<string> logLines, string claimTitle)
    {
        try
        {
            var logDir = _appPaths.LogsPath;
            Directory.CreateDirectory(logDir);
            var logFile = Path.Combine(logDir, "pos-export-log.txt");
            var header = new List<string>
            {
                $"=== POS Export Log — {DateTime.Now:yyyy-MM-dd HH:mm:ss} ===",
                $"Hakediş: {claimTitle}",
                $"POS dosyası: {PosFilePath}",
                $"POS dosyası mevcut: {File.Exists(PosFilePath)}",
                $"Exact kayıt sayısı: {_exactMap.Count}",
                $"Entry kayıt sayısı: {_entries.Count}",
                "--- İlk 5 POS kaydı ---"
            };
            header.AddRange(_entries.Take(5).Select(e => $"  [{e.PosNo,6}] {e.Key[..Math.Min(60, e.Key.Length)]}"));
            header.Add("--- Export kalemleri ---");
            header.AddRange(logLines);
            header.Add(string.Empty);

            lock (_logLock)
                File.AppendAllLines(logFile, header);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "POS export log yazılamadı.");
        }
    }

    // --- Özel kural 1: Sülyen / Polisan boru boyanması ---
    private static string? TryGetPaintPos(string description, string? autoGeneratedType = null)
    {
        bool isPaintAutoType = autoGeneratedType is "BlackSteelPipeRedOxidePaint" or "BlackSteelPipePolisanPaint";
        var raw = Normalize(description);
        bool hasSulyen  = raw.Contains("SULYEN") && raw.Contains("BOYAN");
        bool hasPolisan = raw.Contains("POLISAN");
        if (!hasSulyen && !hasPolisan && !isPaintAutoType) return null;

        bool isSmall  = raw.Contains("3 4") || raw.Contains("1 1 2") || raw.Contains("11 2");
        bool isLarge  = raw.Contains("10");
        bool isMedium = !isSmall && !isLarge && raw.Contains("2") && raw.Contains("4");

        bool isPolisanPaint = hasPolisan || autoGeneratedType == "BlackSteelPipePolisanPaint";
        if (isPolisanPaint)
        {
            if (isSmall)  return "24,01";
            if (isMedium) return "24,02";
            return null;
        }

        bool isSulyenPaint = hasSulyen || autoGeneratedType == "BlackSteelPipeRedOxidePaint";
        if (isSulyenPaint)
        {
            if (isSmall)  return "23,01";
            if (isMedium) return "23,02";
            if (isLarge)  return "23,03";
        }
        return null;
    }

    // --- Özel kural 2: Flexible hava kanalı ---
    private static string? TryGetFlexiPos(string description)
    {
        var text = Normalize(description);
        bool isFlexi   = text.Contains("FLEXI") || text.Contains("FLEXIBLE");
        bool isAirDuct = text.Contains("HAVA KANALI") || text.Contains("HAVALANDIRMA");
        if (!isFlexi || !isAirDuct) return null;

        string? diameter = null;
        var diameterTokens = new (string Diam, string Token)[]
        {
            ("102", "O102"), ("127", "O127"), ("140", "O140"),
            ("152", "O152"), ("160", "O160"), ("185", "O185"),
            ("203", "O203"), ("229", "O229"), ("254", "O254"),
        };
        foreach (var (d, token) in diameterTokens)
            if (text.Contains(token)) { diameter = d; break; }

        if (diameter is null) return null;

        // ÖNEMLİ: izolesiz ÖNCE kontrol edilmeli (içinde "izoleli" geçiyor)
        if (text.Contains("IZOLESIZ"))
            return diameter switch
            {
                "102" => "2,11", "127" => "2,12", "140" => "2,13",
                "152" => "2,14", "160" => "2,15", "185" => "2,16",
                "203" => "2,17", "229" => "2,18", "254" => "2,19",
                _ => null
            };

        if (text.Contains("IZOLELI"))
            return diameter switch
            {
                "102" => "2,21", "127" => "2,22", "140" => "2,23",
                "152" => "2,24", "160" => "2,25", "185" => "2,26",
                "203" => "2,27", "229" => "2,28", "254" => "2,29",
                _ => null
            };

        return null;
    }

    // --- Normalize ---
    internal static string Normalize(string s)
    {
        if (string.IsNullOrWhiteSpace(s)) return string.Empty;
        s = new string(s.Select(c => c switch
        {
            (char)305 or (char)304 => (char)105,   // ı/İ → i
            (char)287 or (char)286 => (char)103,   // ğ/Ğ → g
            (char)252 or (char)220 => (char)117,   // ü/Ü → u
            (char)351 or (char)350 => (char)115,   // ş/Ş → s
            (char)246 or (char)214 => (char)111,   // ö/Ö → o
            (char)231 or (char)199 => (char)99,    // ç/Ç → c
            (char)248 or (char)216 => (char)111,   // ø/Ø → o
            _ => c
        }).ToArray());
        s = s.ToUpperInvariant();
        s = s.Replace("°", "").Replace("º", "").Replace("℃", ""); // derece sembolleri
        s = s.Replace("\"", "").Replace("“", "").Replace("”", "");      // tırnak işaretleri
        s = s.Replace("≤", "").Replace("≥", "");                         // ≤ ≥
        s = Regex.Replace(s, @"[-\(\)\.\,\/\\<>=;:!?*%@#]", " ");
        s = Regex.Replace(s, @"\s+", " ").Trim();
        return s;
    }

    private static string NormalizeHeader(string h)
    {
        h = h.Replace((char)305, (char)73).Replace((char)304, (char)73)
             .Replace((char)287, (char)71).Replace((char)286, (char)71)
             .Replace((char)252, (char)85).Replace((char)220, (char)85)
             .Replace((char)351, (char)83).Replace((char)350, (char)83)
             .Replace((char)246, (char)79).Replace((char)214, (char)79)
             .Replace((char)231, (char)67).Replace((char)199, (char)67);
        return h.ToUpperInvariant().Trim();
    }
}
