namespace HakedisOtomasyon.Domain.Entities;

public class ServiceItem
{
    public int Id { get; set; }
    public int ServiceFormId { get; set; }
    public string Description { get; set; } = string.Empty;
    public decimal Quantity { get; set; } = 1;
    public string Unit { get; set; } = "Ad";
    public decimal MaterialPrice { get; set; }
    public decimal LaborPrice { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal TotalPrice { get; set; }
    public bool IsInvoiceBased { get; set; }
    public int? InvoiceId { get; set; }
    public int SortOrder { get; set; }
    public bool IsManualEntry { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? AutoGeneratedType { get; set; }
    public string? AutoRuleTrigger { get; set; }
    public string? ExportDescription { get; set; }
    public string ItemKey { get; set; } = string.Empty;
    public string? ParentItemKey { get; set; }

    // ── Döviz bazlı kalemler (BDTX / BDKF) ──────────────────────────────────
    public bool IsCurrencyBased { get; set; }
    public string? CurrencyCode { get; set; }           // "USD"
    public decimal? ListPriceUsd { get; set; }          // BVN Liste fiyatı (USD)
    public decimal? DiscountRate { get; set; }          // 0.20 = %20 iskonto
    public decimal? DiscountedUsdPrice { get; set; }    // İskontolu USD fiyatı
    public decimal? ExchangeRate { get; set; }          // Kullanılan kur (₺/USD)
    public DateTime? ExchangeRateDate { get; set; }     // Kur tarihi (seçilen)
    public DateTime? ExchangeRateActualDate { get; set; } // Gerçek bülten tarihi
    public string? ExchangeRateSource { get; set; }     // "TCMB" | "Manuel"

    public ServiceForm ServiceForm { get; set; } = null!;
    public Invoice? Invoice { get; set; }
}
