using HakedisOtomasyon.Application.DTOs;
using HakedisOtomasyon.Domain.Enums;

namespace HakedisOtomasyon.Application.Interfaces;

/// <summary>
/// Bir mekanik disipline (Yangın, Klima, Asansör, Soğutma) özel otomatik kalem üretme
/// ve Excel export sınıflandırma kurallarını tanımlayan ortak arayüz.
/// Her disiplinin kendi kuralları kendi sınıfında izole çalışır — aktif disiplin
/// farklıysa bu kurallar hiç çağrılmaz (bkz. IDisciplineCalculationRuleFactory).
/// </summary>
public interface IDisciplineCalculationRules
{
    MechanicalDiscipline Discipline { get; }

    /// <summary>
    /// Verilen servis kalemi listesindeki TÜM otomatik (fittings/boya/izolasyon) satırlarını
    /// sıfırdan yeniden hesaplar. Liste parametre olarak verilen referans ÜZERİNDE
    /// mutasyona uğrar (Blazor'daki @bind-Items davranışını korumak için) ve aynı
    /// referans geri döner.
    /// </summary>
    Task<List<ServiceItemDto>> ApplyAutomaticItemsAsync(List<ServiceItemDto> items, ProgressClaimDto? claim);

    /// <summary>
    /// Fiyat listesinden yeni bir kalem seçildiğinde, bu disiplin için hangi otomatik kuralın
    /// (AutoRuleTrigger) tetikleneceğini belirler ve gerekiyorsa newItem üzerinde
    /// ExportDescription gibi ek alanları doldurur.
    /// </summary>
    void ApplyTriggerForNewItem(ServiceItemDto newItem, PriceItemDto priceItem);

    /// <summary>Bu fiyat kalemi döviz bazlı (örn. BDTX/BDKF) özel hesaplama gerektiriyor mu?</summary>
    bool IsCurrencyBasedItem(PriceItemDto priceItem);

    /// <summary>
    /// Excel exportta bu kalemin hangi bölüme yazılacağını döner (örn. "HAVALANDIRMA", "YANGIN").
    /// null ise bu disiplin kalemle ilgilenmiyor demektir — çağıran taraf varsayılan davranışı uygular.
    /// </summary>
    string? ResolveSectionName(string description, string? autoGeneratedType, bool isInvoiceBased);

    /// <summary>
    /// tableKey: "BDKF" | "BDTX" | "FLEXIVA" — bu açıklama Excel'e ilgili referans tablo
    /// görselinin eklenmesini gerektiriyor mu?
    /// </summary>
    bool ShouldIncludeReferenceTable(string description, string tableKey);
}
