namespace HakedisOtomasyon.Application.Interfaces;

/// <summary>
/// MasterData\POS_Malzeme_Eslesme.xlsx dosyasindan okunan
/// malzeme aciklamasi -> POS numarasi eslestirme servisi.
/// Kullanici bu dosyayi duzenleyerek yeni POS numaralari ekleyebilir.
/// </summary>
public interface IPosMappingService
{
    /// <summary>
    /// Aktif POS dosyasinin tam yolu.
    /// </summary>
    string PosFilePath { get; }

    /// <summary>
    /// Verilen malzeme aciklamasi icin POS numarasini dondurur.
    /// Eslesme bulunamazsa null doner; uygulama patlamaz.
    /// </summary>
    string? GetPosNo(string description, string? autoGeneratedType = null);

    /// <summary>
    /// Export sirasinda cagrilir: haritayi tazeler, POS bulur, log listesine ekler.
    /// Bulunamazsa bos string doner (null degil).
    /// </summary>
    string ResolvePosForExport(string description, string? autoGeneratedType, List<string>? exportLog);

    /// <summary>
    /// POS haritasini yeniden yukler.
    /// </summary>
    void Reload();

    /// <summary>
    /// Export sonunda pos-export-log.txt dosyasina yazar.
    /// </summary>
    void WriteExportLog(List<string> logLines, string claimTitle);
}
