namespace HakedisOtomasyon.Application.DTOs;

public class ServiceItemDto
{
    public int Id { get; set; }
    public int ServiceFormId { get; set; }
    public string Description { get; set; } = string.Empty;
    public decimal Quantity { get; set; } = 1;
    public string Unit { get; set; } = "Ad";
    public decimal MaterialPrice { get; set; }
    public decimal LaborPrice { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal TotalPrice { get; set; }
    public bool IsInvoiceBased { get; set; }
    public int? InvoiceId { get; set; }
    public int SortOrder { get; set; }
    public bool IsManualEntry { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? AutoGeneratedType { get; set; }  // "Fittings" | "InsulationMounting"
    public string? AutoRuleTrigger { get; set; }    // trigger on parent: "Fittings" | "InsulationMounting" | "FlexivaAir"
    public string? ExportDescription { get; set; }
    public Guid LocalId { get; set; } = Guid.NewGuid();
    public Guid? ParentLocalId { get; set; }

    // -- Doviz bazli kalemler (BDTX / BDKF) -----------------------------------------------
    public bool IsCurrencyBased { get; set; }
    public string? CurrencyCode { get; set; }
    public decimal? ListPriceUsd { get; set; }
    public decimal? DiscountRate { get; set; }
    public decimal? DiscountedUsdPrice { get; set; }
    public decimal? ExchangeRate { get; set; }
    public DateTime? ExchangeRateDate { get; set; }
    public DateTime? ExchangeRateActualDate { get; set; }
    public string? ExchangeRateSource { get; set; }

    /// <summary>
    /// POS numarasi -- Excel exportta A kolonunda gosterilir.
    /// Program arayuzunde gorunmez; export sirasinda PosMappingService tarafindan doldurulur.
    /// </summary>
    public string? PosNo { get; set; }

    public void Recalculate()
    {
        UnitPrice = MaterialPrice + LaborPrice;
        TotalPrice = UnitPrice * Quantity;
    }
}