using HakedisOtomasyon.Application.DTOs;
using HakedisOtomasyon.Application.Interfaces;
using HakedisOtomasyon.Domain.Enums;
using Microsoft.Extensions.Logging;

namespace HakedisOtomasyon.Infrastructure.Services.Calculation;

/// <summary>
/// Yangın disiplinine özel otomatik kalem üretme ve Excel sınıflandırma kuralları.
/// Bu sınıf, eskiden ServiceItemGrid.razor ve ExcelExportService.cs içine dağılmış olan
/// fittings/boya/izolasyon/BDKF/BDTX/Flexiva mantığının TAŞINDIĞI tek merkezi yerdir.
/// Mevcut davranış birebir korunmuştur — sadece konum ve çağrı şekli değişmiştir.
/// </summary>
public class FireCalculationRules : IDisciplineCalculationRules
{
    private readonly IPriceListService _priceListService;
    private readonly IDisciplineProfileService _disciplineProfiles;
    private readonly ILogger<FireCalculationRules> _logger;

    public MechanicalDiscipline Discipline => MechanicalDiscipline.Fire;

    // Sülyen/Polisan fiyat kalemleri — bir kerelik yüklenir, sonraki çağrılarda önbellekten kullanılır.
    private PriceItemDto? _sulyenSmallPriceItem;
    private PriceItemDto? _sulyenMediumPriceItem;
    private PriceItemDto? _sulyenLargePriceItem;
    private bool _sulyenPricesCached;
    private PriceItemDto? _polisanSmallPriceItem;
    private PriceItemDto? _polisanMediumPriceItem;
    private PriceItemDto? _polisanLargePriceItem;
    private bool _polisanPricesCached;

    public FireCalculationRules(
        IPriceListService priceListService,
        IDisciplineProfileService disciplineProfiles,
        ILogger<FireCalculationRules> logger)
    {
        _priceListService = priceListService;
        _disciplineProfiles = disciplineProfiles;
        _logger = logger;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Yeni kalem eklenirken tetiklenecek AutoRuleTrigger belirleme
    // ─────────────────────────────────────────────────────────────────────

    public void ApplyTriggerForNewItem(ServiceItemDto newItem, PriceItemDto priceItem)
    {
        if (IsGalvanizedDuctFittingRequired(priceItem))
            newItem.AutoRuleTrigger = "GalvanizedDuct";
        else if (IsPipeInsulationItem(priceItem))
            newItem.AutoRuleTrigger = "InsulationMounting";
        else if (IsFlexivaAirItem(priceItem))
        {
            newItem.AutoRuleTrigger = "FlexivaAir";
            newItem.ExportDescription = GenerateFlexivaExportDescription(priceItem);
        }
        else if (IsSiyahBoruGroup30(priceItem))
            newItem.AutoRuleTrigger = "SiyahBoruGroup30";
        else if (IsSiyahBoruGroup80(priceItem))
            newItem.AutoRuleTrigger = "SiyahBoruGroup80";
        else if (IsDikisliGalvanizliCelikBoruItem(priceItem))
            newItem.AutoRuleTrigger = "DikisliGalvanizliCelikBoru";
    }

    public bool IsCurrencyBasedItem(PriceItemDto priceItem)
    {
        if (priceItem.IsCurrencyBased) return true;
        var desc = Nrm(priceItem.Description);
        var cat  = Nrm(priceItem.MainCategory ?? "");
        var sub  = Nrm(priceItem.SubCategory ?? "");
        var inv  = Nrm(priceItem.InvoiceDescription ?? "");
        return desc.Contains("BDTX") || desc.Contains("BDKF") ||
               cat.Contains("BDTX")  || cat.Contains("BDKF")  ||
               sub.Contains("BDTX")  || sub.Contains("BDKF")  ||
               inv.Contains("BDTX")  || inv.Contains("BDKF");
    }

    // ─────────────────────────────────────────────────────────────────────
    // Tüm otomatik kalemleri sıfırdan yeniden hesapla (fittings + boya + izolasyon)
    // ─────────────────────────────────────────────────────────────────────

    public async Task<List<ServiceItemDto>> ApplyAutomaticItemsAsync(List<ServiceItemDto> items, ProgressClaimDto? claim)
    {
        int beforeAutoCount = items.Count(x => x.IsAutoGenerated);

        ApplyGroupFittingsRules(items);
        ApplyInsulationMountingRules(items);
        await RecalculateBlackSteelPipePaintRowsAsync(items);

        for (int i = 0; i < items.Count; i++) items[i].SortOrder = i + 1;

        int afterAutoCount = items.Count(x => x.IsAutoGenerated);
        var addedTypes = items.Where(x => x.IsAutoGenerated)
            .Select(x => x.AutoGeneratedType ?? "?")
            .Distinct()
            .ToList();
        WriteCalculationLog(beforeAutoCount, afterAutoCount, addedTypes);

        return items;
    }

    private void WriteCalculationLog(int before, int after, List<string> addedTypes)
    {
        try
        {
            var logDir = Path.Combine(_disciplineProfiles.GetCommonPath(), "Logs");
            Directory.CreateDirectory(logDir);
            var logFile = Path.Combine(logDir, "calculation-rules-log.txt");
            var lines = new[]
            {
                $"=== {DateTime.Now:yyyy-MM-dd HH:mm:ss} ===",
                $"Aktif Disiplin: {Discipline}",
                $"Çalışan Kural Sınıfı: {nameof(FireCalculationRules)}",
                $"Önceki otomatik kalem sayısı: {before}",
                $"Sonraki otomatik kalem sayısı: {after}",
                $"AutoGeneratedType değerleri: {string.Join(", ", addedTypes)}",
                string.Empty
            };
            File.AppendAllLines(logFile, lines);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "calculation-rules-log.txt yazılamadı.");
        }
    }

    /// <summary>
    /// Siyah boru (%30/%80), dikişli galvanizli çelik boru (%40) ve galvaniz hava
    /// kanalı (%30, sadece malzeme) grup fittings satırlarını sıfırdan yeniden hesaplar.
    /// </summary>
    private static void ApplyGroupFittingsRules(List<ServiceItemDto> items)
    {
        items.RemoveAll(x => x.IsAutoGenerated &&
            (x.AutoGeneratedType == "BlackPipeFitting30"   || x.AutoGeneratedType == "BlackPipeFitting80" ||
             x.AutoGeneratedType == "SiyahBoruFittings30"  || x.AutoGeneratedType == "SiyahBoruFittings80" ||
             x.AutoGeneratedType == "GalvanizedSteelPipeFitting40" ||
             x.AutoGeneratedType == "GalvanizedDuctFitting30"));

        // Grup 30 (×0.30): 1", 1 1/4", 1 1/2", 2"
        var lastIdx30 = -1;
        decimal total30 = 0;
        for (int i = 0; i < items.Count; i++)
        {
            var it30 = items[i];
            if (it30.IsAutoGenerated) continue;
            bool inGroup30 = it30.AutoRuleTrigger == "SiyahBoruGroup30" ||
                             (it30.AutoRuleTrigger == null && IsSiyahBoruGroup30FromDesc(it30.Description));
            if (inGroup30) { total30 += it30.TotalPrice; lastIdx30 = i; }
        }
        if (lastIdx30 >= 0)
        {
            items.Insert(lastIdx30 + 1, new ServiceItemDto
            {
                LocalId = Guid.NewGuid(),
                Description = "Fittings malzeme bedeli",
                Quantity = 30, Unit = "%",
                MaterialPrice = 0, LaborPrice = 0, UnitPrice = 0,
                TotalPrice = total30 * 0.30m,
                IsAutoGenerated = true,
                AutoGeneratedType = "BlackPipeFitting30"
            });
        }

        // Grup 80 (×0.80): 2 1/2", 3", 4", 5"
        var lastIdx80 = -1;
        decimal total80 = 0;
        for (int i = 0; i < items.Count; i++)
        {
            var it80 = items[i];
            if (it80.IsAutoGenerated) continue;
            bool inGroup80 = it80.AutoRuleTrigger == "SiyahBoruGroup80" ||
                             (it80.AutoRuleTrigger == null && IsSiyahBoruGroup80FromDesc(it80.Description));
            if (inGroup80) { total80 += it80.TotalPrice; lastIdx80 = i; }
        }
        if (lastIdx80 >= 0)
        {
            items.Insert(lastIdx80 + 1, new ServiceItemDto
            {
                LocalId = Guid.NewGuid(),
                Description = "Fittings malzeme bedeli",
                Quantity = 80, Unit = "%",
                MaterialPrice = 0, LaborPrice = 0, UnitPrice = 0,
                TotalPrice = total80 * 0.80m,
                IsAutoGenerated = true,
                AutoGeneratedType = "BlackPipeFitting80"
            });
        }

        // Dikişli galvanizli çelik boru grubu (×0.40)
        var lastIdxGalv = -1;
        decimal totalGalv = 0;
        for (int i = 0; i < items.Count; i++)
        {
            var itGalv = items[i];
            if (itGalv.IsAutoGenerated) continue;
            bool inGroupGalv = IsDikisliGalvanizliCelikBoruFromDesc(itGalv.Description);
            if (inGroupGalv) { totalGalv += itGalv.TotalPrice; lastIdxGalv = i; }
        }
        if (lastIdxGalv >= 0)
        {
            items.Insert(lastIdxGalv + 1, new ServiceItemDto
            {
                LocalId = Guid.NewGuid(),
                Description = "Fittings malzeme bedeli",
                Quantity = 40, Unit = "%",
                MaterialPrice = 0, LaborPrice = 0, UnitPrice = 0,
                TotalPrice = totalGalv * 0.40m,
                IsAutoGenerated = true,
                AutoGeneratedType = "GalvanizedSteelPipeFitting40"
            });
        }

        // Galvaniz Sac Dikdörtgen Hava Kanalı grubu (×0.30, SADECE malzeme tutarı)
        var lastIdxDuct = -1;
        decimal totalDuctMat = 0;
        for (int i = 0; i < items.Count; i++)
        {
            var itDuct = items[i];
            if (itDuct.IsAutoGenerated) continue;
            bool inGroupDuct =
                itDuct.AutoRuleTrigger == "GalvanizedDuct" ||
                itDuct.AutoRuleTrigger == "Fittings" ||
                (itDuct.AutoRuleTrigger is null && IsGalvanizedDuctFittingFromDesc(itDuct.Description));
            if (inGroupDuct)
            {
                totalDuctMat += itDuct.Quantity * itDuct.MaterialPrice;
                lastIdxDuct = i;
            }
        }
        if (lastIdxDuct >= 0 && totalDuctMat > 0)
        {
            items.Insert(lastIdxDuct + 1, new ServiceItemDto
            {
                LocalId = Guid.NewGuid(),
                Description = "Fittings malzeme bedeli",
                Quantity = 30, Unit = "%",
                MaterialPrice = 0, LaborPrice = 0, UnitPrice = 0,
                TotalPrice = totalDuctMat * 0.30m,
                IsAutoGenerated = true,
                AutoGeneratedType = "GalvanizedDuctFitting30"
            });
        }
    }

    /// <summary>
    /// Cam yünü/kauçuk izolasyon kalemleri için %15 montaj satırını her parent'ın
    /// hemen altına sıfırdan yeniden ekler.
    /// </summary>
    private static void ApplyInsulationMountingRules(List<ServiceItemDto> items)
    {
        items.RemoveAll(x => x.IsAutoGenerated && x.AutoGeneratedType == "InsulationMounting");

        var insertions = new List<(int afterIdx, ServiceItemDto row)>();
        for (int i = 0; i < items.Count; i++)
        {
            var parent = items[i];
            if (parent.IsAutoGenerated) continue;
            if (parent.AutoRuleTrigger != "InsulationMounting") continue;

            insertions.Add((i, new ServiceItemDto
            {
                LocalId = Guid.NewGuid(),
                ParentLocalId = parent.LocalId,
                Description = "İzolasyon montaj malzemesi bedeli",
                Quantity = 15,
                Unit = "%",
                MaterialPrice = 0, LaborPrice = 0, UnitPrice = 0,
                TotalPrice = parent.Quantity * parent.MaterialPrice * 0.15m,
                IsAutoGenerated = true,
                AutoGeneratedType = "InsulationMounting"
            }));
        }

        // Yüksek indeksten alta doğru ekle — daha alttaki ekler üst indeksleri kaydırmasın.
        foreach (var (afterIdx, row) in insertions.OrderByDescending(x => x.afterIdx))
            items.Insert(afterIdx + 1, row);
    }

    /// <summary>
    /// DİKİŞLİ SİYAH ÇELİK BORU kalemleri için çap aralığına göre SÜLYEN + POLİSAN
    /// boya satırlarını sıfırdan yeniden hesaplar.
    /// </summary>
    private async Task RecalculateBlackSteelPipePaintRowsAsync(List<ServiceItemDto> items)
    {
        items.RemoveAll(x => x.IsAutoGenerated &&
            (x.AutoGeneratedType == "BlackSteelPipeRedOxidePaint" ||
             x.AutoGeneratedType == "BlackSteelPipePolisanPaint"));

        decimal totalSmall = 0m, totalMedium = 0m, totalLarge = 0m;
        int lastIdxSmall = -1, lastIdxMedium = -1, lastIdxLarge = -1;

        for (int i = 0; i < items.Count; i++)
        {
            var it = items[i];
            if (it.IsAutoGenerated) continue;
            if (!IsDikisliSiyahCelikBoruFromDesc(it.Description)) continue;

            var d = ExtractPipeDiameter(NrmPipe(it.Description));
            if (!d.HasValue) continue;

            if (d.Value >= 0.5m && d.Value <= 1.5m) { totalSmall += it.Quantity; lastIdxSmall = i; }
            else if (d.Value >= 2m && d.Value <= 4m) { totalMedium += it.Quantity; lastIdxMedium = i; }
            else if (d.Value > 4m && d.Value <= 10m) { totalLarge += it.Quantity; lastIdxLarge = i; }
        }

        if (totalSmall <= 0 && totalMedium <= 0 && totalLarge <= 0) return;

        await EnsureSulyenPricesCachedAsync();
        await EnsurePolisanPricesCachedAsync();

        var insertions = new List<(int afterIdx, ServiceItemDto? sulyenRow, ServiceItemDto? polisanRow)>();

        if (totalSmall > 0)
        {
            var pair = BuildPaintPair(
                "3/4\" - 1 1/2\" arası (1 1/2\" dahil)", totalSmall,
                _sulyenSmallPriceItem, _polisanSmallPriceItem);
            if (pair.sulyenRow != null || pair.polisanRow != null)
                insertions.Add((lastIdxSmall, pair.sulyenRow, pair.polisanRow));
        }
        if (totalMedium > 0)
        {
            var pair = BuildPaintPair(
                "2\" - 4\" arası (4\" dahil)", totalMedium,
                _sulyenMediumPriceItem, _polisanMediumPriceItem);
            if (pair.sulyenRow != null || pair.polisanRow != null)
                insertions.Add((lastIdxMedium, pair.sulyenRow, pair.polisanRow));
        }
        if (totalLarge > 0)
        {
            var pair = BuildPaintPair(
                "4\" - 10\" arası (10\" dahil)", totalLarge,
                _sulyenLargePriceItem, _polisanLargePriceItem);
            if (pair.sulyenRow != null || pair.polisanRow != null)
                insertions.Add((lastIdxLarge, pair.sulyenRow, pair.polisanRow));
        }

        // Polisan'ı önce, sülyen'i sonra aynı indekse ekle → sülyen polisan'dan önce görünür.
        foreach (var (afterIdx, sulyenRow, polisanRow) in insertions.OrderByDescending(x => x.afterIdx))
        {
            if (polisanRow != null) items.Insert(afterIdx + 1, polisanRow);
            if (sulyenRow != null) items.Insert(afterIdx + 1, sulyenRow);
        }
    }

    private static (ServiceItemDto? sulyenRow, ServiceItemDto? polisanRow) BuildPaintPair(
        string rangeLabel, decimal quantity, PriceItemDto? sulyenPrice, PriceItemDto? polisanPrice)
    {
        ServiceItemDto? sulyenRow = null;
        ServiceItemDto? polisanRow = null;

        if (sulyenPrice is not null)
        {
            sulyenRow = new ServiceItemDto
            {
                LocalId = Guid.NewGuid(),
                Description = $"SÜLYEN BORU BOYANMASI - {rangeLabel}",
                Quantity = quantity,
                Unit = string.IsNullOrWhiteSpace(sulyenPrice.Unit) ? "m" : sulyenPrice.Unit,
                MaterialPrice = sulyenPrice.MaterialPrice,
                LaborPrice = sulyenPrice.LaborPrice,
                IsAutoGenerated = true,
                AutoGeneratedType = "BlackSteelPipeRedOxidePaint",
            };
            sulyenRow.Recalculate();
        }
        if (polisanPrice is not null)
        {
            polisanRow = new ServiceItemDto
            {
                LocalId = Guid.NewGuid(),
                Description = $"SÜLYEN BORU BOYANMASI - {rangeLabel} - POLİSAN",
                Quantity = quantity,
                Unit = string.IsNullOrWhiteSpace(polisanPrice.Unit) ? "m" : polisanPrice.Unit,
                MaterialPrice = polisanPrice.MaterialPrice,
                LaborPrice = polisanPrice.LaborPrice,
                IsAutoGenerated = true,
                AutoGeneratedType = "BlackSteelPipePolisanPaint",
            };
            polisanRow.Recalculate();
        }
        return (sulyenRow, polisanRow);
    }

    private async Task EnsureSulyenPricesCachedAsync()
    {
        if (_sulyenPricesCached) return;
        _sulyenPricesCached = true;
        try
        {
            var items = await _priceListService.SearchAsync("SÜLYEN BORU BOYANMASI");
            foreach (var r in items)
            {
                var fullNrm = Nrm($"{r.MainCategory ?? ""} {r.Description} {r.SubCategory ?? ""} {r.InvoiceDescription ?? ""}");
                if (!fullNrm.Contains("SULYEN")) continue;
                if (fullNrm.Contains("POLISAN")) continue;

                var descNrmPipe = NrmPipe(r.Description);
                if (_sulyenSmallPriceItem is null && descNrmPipe.Contains("3/4"))
                    _sulyenSmallPriceItem = r;
                else if (_sulyenLargePriceItem is null && descNrmPipe.Contains("10"))
                    _sulyenLargePriceItem = r;
                else if (_sulyenMediumPriceItem is null && !descNrmPipe.Contains("3/4") && !descNrmPipe.Contains("10"))
                    _sulyenMediumPriceItem = r;
            }
        }
        catch { /* Fiyat listesine erişilemezse sessizce atla */ }
    }

    private async Task EnsurePolisanPricesCachedAsync()
    {
        if (_polisanPricesCached) return;
        _polisanPricesCached = true;
        try
        {
            var items = await _priceListService.SearchAsync("SÜLYEN BORU BOYANMASI");
            foreach (var r in items)
            {
                var fullNrm = Nrm($"{r.MainCategory ?? ""} {r.Description} {r.SubCategory ?? ""} {r.InvoiceDescription ?? ""}");
                if (!fullNrm.Contains("SULYEN")) continue;
                if (!fullNrm.Contains("POLISAN")) continue;

                var descNrmPipe = NrmPipe(r.Description);
                if (_polisanSmallPriceItem is null && descNrmPipe.Contains("3/4"))
                    _polisanSmallPriceItem = r;
                else if (_polisanLargePriceItem is null && descNrmPipe.Contains("10"))
                    _polisanLargePriceItem = r;
                else if (_polisanMediumPriceItem is null && !descNrmPipe.Contains("3/4") && !descNrmPipe.Contains("10"))
                    _polisanMediumPriceItem = r;
            }
        }
        catch { /* Fiyat listesine erişilemezse sessizce atla */ }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Excel export — bölüm (section) ve referans tablo tespiti
    // ─────────────────────────────────────────────────────────────────────

    public string? ResolveSectionName(string description, string? autoGeneratedType, bool isInvoiceBased)
    {
        if (isInvoiceBased || autoGeneratedType == "InvoicePlus10" || Nrm(description).Contains("FATURA +%10"))
            return "DİĞER";

        if (!string.IsNullOrEmpty(autoGeneratedType))
        {
            if (autoGeneratedType is "GalvanizedDuctFitting30" or "InsulationMounting")
                return "HAVALANDIRMA";
            if (autoGeneratedType is "BlackPipeFitting30" or "BlackPipeFitting80" or
                "SiyahBoruFittings30" or "SiyahBoruFittings80" or "GalvanizedSteelPipeFitting40" or
                "BlackSteelPipeRedOxidePaint" or "BlackSteelPipePolisanPaint")
                return "YANGIN";
        }

        if (IsHvacDesc(description)) return "HAVALANDIRMA";
        if (IsFireDesc(description)) return "YANGIN";

        // Fiyat listesi ürünleri varsayılan olarak yangın tesisatı sayılır.
        return "YANGIN";
    }

    public bool ShouldIncludeReferenceTable(string description, string tableKey)
    {
        var s = Nrm(description);
        return tableKey.ToUpperInvariant() switch
        {
            "FLEXIVA" => IsFlexivaDesc(description),
            "BDKF"    => s.Contains("BDKF"),
            "BDTX"    => s.Contains("BDTX"),
            _         => false
        };
    }

    private static bool IsFlexivaDesc(string desc)
    {
        var s = Nrm(desc);
        return s.Contains("FLEXIVA")
            || s.Contains("IZOLELI HAVA")
            || s.Contains("IZOLESIZ HAVA")
            || s.Contains("HIJYENIK")
            || s.Contains("SONO")
            || s.Contains("HAVALANDIRMA FLEXI");
    }

    private static bool IsHvacDesc(string desc)
    {
        var s = Nrm(desc);
        return s.Contains("BDTX") || s.Contains("BDKF")
            || s.Contains("KANAL TIPI FAN") || s.Contains("BVN")
            || s.Contains("FLEXIVA")
            || s.Contains("HAVALANDIRMA")
            || s.Contains("HAVA KANALI") || s.Contains("SPIRO")
            || s.Contains("MENFEZ")
            || s.Contains("DAMPER") || s.Contains("PANJUR")
            || s.Contains("DIFUZOR") || s.Contains("ANEMOSTAT") || s.Contains("ANEMOSTAD")
            || (s.Contains("FAN") && !s.Contains("YANGIN"))
            || s.Contains("HAVA DEBISI") || s.Contains("AKIS OLCER")
            || s.Contains("T BAGLANTI") || s.Contains("KANAL BAGLANTI")
            || s.Contains("GALVANIZ SAC")
            || s.Contains("IZOLELI HAVA") || s.Contains("IZOLESIZ HAVA")
            || s.Contains("LEVHA IZOLASYON")
            || s.Contains("DIRSEK")
            || s.Contains("FILTRE")
            || s.Contains("BORU YALITIMI")
            || s.Contains("YALITIM")
            || s.Contains("FLEXIBLE BAGLANTI HORTUMU")
            || s.Contains("PISLIK TUTUCU")
            || s.Contains("MANOMETRE")
            || s.Contains("TERMOMETRE")
            || s.Contains("OTOMATIK HAVA ATMA")
            || s.Contains("KAYNAKLI IMALAT")
            || s.Contains("TEMIZ SU BORULARI")
            || s.Contains("DRENAJ BORULARI")
            || s.Contains("ODE ") || s.StartsWith("ODE")
            || s.Contains("AYVAZ")
            || s.Contains("PAKKENS")
            || s.Contains("ECA ") || s.StartsWith("ECA");
    }

    private static bool IsFireDesc(string desc)
    {
        var s = Nrm(desc);
        return s.Contains("YANGIN") || s.Contains("SPRINKLER") || s.Contains("SPRINK")
            || s.Contains("PENDENT") || s.Contains("UPRIGHT")
            || s.Contains("FLOW SWITCH") || s.Contains("TEST DRENAJ")
            || s.Contains("KELEBEK VANA") || s.Contains("ITFAIYE")
            || (s.Contains("DIKISLI") && s.Contains("SIYAH"))
            || (s.Contains("SIYAH") && s.Contains("CELIK") && s.Contains("BORU"))
            || (s.Contains("DIKISLI") && s.Contains("GALVANIZLI"))
            || (s.Contains("GALVANIZLI") && s.Contains("CELIK") && s.Contains("BORU"))
            || s.Contains("SULYEN") || s.Contains("POLISAN") || s.Contains("BOYANMASI")
            || s.Contains("MANIFOLD") || s.Contains("KOLLEKTOR");
    }

    // ─────────────────────────────────────────────────────────────────────
    // Fiyat kalemi tespit yardımcıları (ServiceItemGrid.razor'dan taşındı)
    // ─────────────────────────────────────────────────────────────────────

    private static bool IsGalvanizedDuctFittingRequired(PriceItemDto item)
    {
        var mainCat = Nrm(item.MainCategory ?? "");
        var desc    = Nrm(item.Description);
        var inv     = Nrm(item.InvoiceDescription ?? "");

        bool hasGalvanizKanal =
            (mainCat.Contains("GALVANIZ") && mainCat.Contains("KANAL")) ||
            (desc.Contains("GALVANIZ")    && desc.Contains("KANAL"))    ||
            (inv.Contains("GALVANIZ")     && inv.Contains("KANAL"));
        if (!hasGalvanizKanal) return false;

        var combined = $"{desc} {inv}";

        if (combined.Contains("0.5 MM") || combined.Contains("0.5MM") ||
            combined.Contains("0,5 MM") || combined.Contains("0,5MM") ||
            combined.Contains("0.6 MM") || combined.Contains("0.6MM") ||
            combined.Contains("0,6 MM") || combined.Contains("0,6MM") ||
            combined.Contains("0.8 MM") || combined.Contains("0.8MM") ||
            combined.Contains("0,8 MM") || combined.Contains("0,8MM") ||
            combined.Contains("1.0 MM") || combined.Contains("1.0MM") ||
            combined.Contains("1,0 MM") || combined.Contains("1,0MM"))
            return true;

        return combined.Contains("<= 250")  || combined.Contains("<=250")  ||
               combined.Contains("<= 499")  || combined.Contains("<=499")  ||
               combined.Contains("<= 500")  || combined.Contains("<=500")  ||
               combined.Contains("<= 990")  || combined.Contains("<=990")  ||
               combined.Contains("<= 1490") || combined.Contains("<=1490") ||
               combined.Contains("EBAD <=5") || combined.Contains("EBAD<=5") ||
               combined.Contains("EBADI <=5") || combined.Contains("EBADI<=5");
    }

    private static bool IsGalvanizedDuctFittingFromDesc(string desc)
    {
        var s = Nrm(desc);
        if (!(s.Contains("GALVANIZ") && s.Contains("KANAL"))) return false;
        return s.Contains("0.5 MM") || s.Contains("0.5MM") ||
               s.Contains("0,5 MM") || s.Contains("0,5MM") ||
               s.Contains("0.6 MM") || s.Contains("0.6MM") ||
               s.Contains("0,6 MM") || s.Contains("0,6MM") ||
               s.Contains("0.8 MM") || s.Contains("0.8MM") ||
               s.Contains("0,8 MM") || s.Contains("0,8MM") ||
               s.Contains("1.0 MM") || s.Contains("1.0MM") ||
               s.Contains("1,0 MM") || s.Contains("1,0MM") ||
               s.Contains("<= 250")  || s.Contains("<=250")  ||
               s.Contains("<= 499")  || s.Contains("<=499")  ||
               s.Contains("<= 990")  || s.Contains("<=990")  ||
               s.Contains("<= 1490") || s.Contains("<=1490");
    }

    private static bool IsPipeInsulationItem(PriceItemDto item)
    {
        var mainCat = Nrm(item.MainCategory ?? "");
        return (mainCat.Contains("CAM YUNU") || mainCat.Contains("KAUCUK")) &&
               mainCat.Contains("BORU") && mainCat.Contains("YALITIM");
    }

    private static bool IsFlexivaAirItem(PriceItemDto item)
    {
        var desc    = Nrm(item.Description);
        var mainCat = Nrm(item.MainCategory ?? "");
        return desc.Contains("FLEXIVA") || mainCat.Contains("FLEXIVA") ||
               desc.Contains("HAVALANDIRMA FLEX") || mainCat.Contains("HAVALANDIRMA FLEX") ||
               (desc.Contains("FLEX") && (desc.Contains("IZOLESIZ") || desc.Contains("IZOLELI")));
    }

    private static string GenerateFlexivaExportDescription(PriceItemDto item)
    {
        const decimal discountRate = 0.30m;
        var discountedPrice = item.MaterialPrice;
        var originalPrice   = discountRate < 1 ? discountedPrice / (1 - discountRate) : discountedPrice;

        var unit = (item.Unit ?? "m").Trim();
        decimal unitQty  = 1;
        string  baseUnit = unit;
        var parts = unit.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length >= 2 &&
            decimal.TryParse(parts[0], System.Globalization.NumberStyles.Number,
                System.Globalization.CultureInfo.InvariantCulture, out var q))
        {
            unitQty  = q;
            baseUnit = parts[1];
        }

        var trCulture = new System.Globalization.CultureInfo("tr-TR");
        var perUnitPrice = unitQty > 0 ? discountedPrice / unitQty : discountedPrice;
        return $"{item.Description} {originalPrice.ToString("N2", trCulture)} TL x %30 iskonto = {discountedPrice.ToString("N2", trCulture)} TL / {unit} = {perUnitPrice.ToString("N2", trCulture)} TL/{baseUnit}";
    }

    private static bool IsSiyahBoruItem(string s) => s.Contains("SIYAH") && s.Contains("BORU");

    private static bool IsSiyahBoruGroup30(PriceItemDto item)
    {
        var s = NrmPipe($"{item.MainCategory ?? ""} {item.Description} {item.InvoiceDescription ?? ""}");
        if (!IsSiyahBoruItem(s)) return false;
        var d = ExtractPipeDiameter(s);
        return d.HasValue && d.Value >= 1m && d.Value <= 2m;
    }

    private static bool IsSiyahBoruGroup80(PriceItemDto item)
    {
        var s = NrmPipe($"{item.MainCategory ?? ""} {item.Description} {item.InvoiceDescription ?? ""}");
        if (!IsSiyahBoruItem(s)) return false;
        var d = ExtractPipeDiameter(s);
        return d.HasValue && d.Value >= 2.5m && d.Value <= 5m;
    }

    private static bool IsSiyahBoruGroup30FromDesc(string desc)
    {
        var s = NrmPipe(desc);
        if (!IsSiyahBoruItem(s)) return false;
        var d = ExtractPipeDiameter(s);
        return d.HasValue && d.Value >= 1m && d.Value <= 2m;
    }

    private static bool IsSiyahBoruGroup80FromDesc(string desc)
    {
        var s = NrmPipe(desc);
        if (!IsSiyahBoruItem(s)) return false;
        var d = ExtractPipeDiameter(s);
        return d.HasValue && d.Value >= 2.5m && d.Value <= 5m;
    }

    private static bool IsDikisliGalvanizliCelikBoruItem(PriceItemDto item)
    {
        var combined = Nrm($"{item.MainCategory ?? ""} {item.Description} {item.InvoiceDescription ?? ""}");
        return combined.Contains("GALVANIZLI") && combined.Contains("CELIK") && combined.Contains("BORU");
    }

    private static bool IsDikisliGalvanizliCelikBoruFromDesc(string desc)
    {
        var s = Nrm(desc);
        return s.Contains("GALVANIZLI") && s.Contains("CELIK") && s.Contains("BORU");
    }

    private static bool IsDikisliSiyahCelikBoruFromDesc(string desc)
    {
        var s = Nrm(desc);
        return s.Contains("DIKISLI") && s.Contains("SIYAH") && s.Contains("BORU");
    }

    /// <summary>
    /// Parses the inch diameter from a normalized pipe description.
    /// Fractional sizes are checked first to prevent false single-digit matches.
    /// </summary>
    private static decimal? ExtractPipeDiameter(string nrmPipeStr)
    {
        var s = nrmPipeStr;
        if (s.Contains("2 1/2")) return 2.5m;
        if (s.Contains("1 1/4")) return 1.25m;
        if (s.Contains("1 1/2")) return 1.5m;
        if (s.Contains("3/4"))   return 0.75m;
        if (s.Contains("1/2"))   return 0.5m;
        if (PipeSizeMatch(s, "10")) return 10m;
        if (PipeSizeMatch(s, "8"))  return 8m;
        if (PipeSizeMatch(s, "6"))  return 6m;
        if (PipeSizeMatch(s, "5"))  return 5m;
        if (PipeSizeMatch(s, "4"))  return 4m;
        if (PipeSizeMatch(s, "3"))  return 3m;
        if (PipeSizeMatch(s, "2"))  return 2m;
        if (PipeSizeMatch(s, "1"))  return 1m;
        return null;
    }

    private static bool PipeSizeMatch(string s, string digit)
    {
        if (s.Contains(digit + "\"")) return true;
        if (s.Contains(digit + " \"")) return true;
        if (s.Contains(digit + " INC")) return true;
        int idx = -1;
        while ((idx = s.IndexOf(digit, idx + 1)) >= 0)
        {
            bool prevOk = idx == 0 || (!char.IsDigit(s[idx - 1]) && s[idx - 1] != '/');
            if (!prevOk) continue;
            int after = idx + digit.Length;
            bool nextOk = after >= s.Length || (!char.IsDigit(s[after]) && s[after] != '/');
            if (nextOk) return true;
        }
        return false;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Normalizasyon yardımcıları
    // ─────────────────────────────────────────────────────────────────────

    internal static string Nrm(string s) =>
        s.Replace('ı', 'I').Replace('İ', 'I')
         .Replace('ğ', 'G').Replace('Ğ', 'G')
         .Replace('ü', 'U').Replace('Ü', 'U')
         .Replace('ş', 'S').Replace('Ş', 'S')
         .Replace('ö', 'O').Replace('Ö', 'O')
         .Replace('ç', 'C').Replace('Ç', 'C')
         .ToUpperInvariant().Trim();

    private static string NrmPipe(string s)
    {
        return Nrm(s)
            .Replace('“', '"').Replace('”', '"')
            .Replace('″', '"').Replace('ʺ', '"')
            .Replace('＂', '"')
            .Replace("½", " 1/2").Replace("¼", " 1/4")
            .Replace("2-1/2", "2 1/2")
            .Replace("1-1/4", "1 1/4")
            .Replace("1-1/2", "1 1/2")
            .Replace("21/2", "2 1/2")
            .Replace("11/4", "1 1/4")
            .Replace("11/2", "1 1/2");
    }
}
