using HakedisOtomasyon.Application.DTOs;
using HakedisOtomasyon.Application.Interfaces;
using HakedisOtomasyon.Domain.Enums;

namespace HakedisOtomasyon.Infrastructure.Services.Calculation;

/// <summary>
/// Klima disiplini henüz aktif değil — otomatik kalem üretmez, Excel sınıflandırması yapmaz.
/// İleride Klima'ya özel kurallar buraya yazılacak.
/// </summary>
public class HvacCalculationRules : IDisciplineCalculationRules
{
    public MechanicalDiscipline Discipline => MechanicalDiscipline.Hvac;

    public Task<List<ServiceItemDto>> ApplyAutomaticItemsAsync(List<ServiceItemDto> items, ProgressClaimDto? claim)
        => Task.FromResult(items);

    public void ApplyTriggerForNewItem(ServiceItemDto newItem, PriceItemDto priceItem) { }

    public bool IsCurrencyBasedItem(PriceItemDto priceItem) => false;

    public string? ResolveSectionName(string description, string? autoGeneratedType, bool isInvoiceBased) => null;

    public bool ShouldIncludeReferenceTable(string description, string tableKey) => false;
}
